<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CSS-D-196" ignored="2" name="Reader Tests" tests="22" failures="11" timestamp="26 Aug 2020 09:30:37 GMT" time="158.243" errors="0">
  <testcase name="transaction" time="41.547" classname="com.concerto.vegaah.test.scenarios.apiTransactions.PartialTransPGHosted"/>
  <testcase name="transaction" time="33.443" classname="com.concerto.vegaah.test.scenarios.apiTransactions.PartialTransPGHosted"/>
  <testcase name="transaction" time="19.74" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted"/>
  <testcase name="transaction" time="0.819" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted"/>
  <testcase name="transaction" time="1.216" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted"/>
  <testcase name="transaction" time="0.909" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.concerto.vegaah.db.methods.ValidateTransactionStatus.QueryApplicationConfig(ValidateTransactionStatus.java:49)
at com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted.transaction(CardedTransPGHosted.java:105)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- transaction -->
  <testcase name="transaction" time="0.779" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.concerto.vegaah.db.methods.ValidateTransactionStatus.QueryApplicationConfig(ValidateTransactionStatus.java:49)
at com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted.transaction(CardedTransPGHosted.java:105)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- transaction -->
  <testcase name="transaction" time="1.126" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted"/>
  <testcase name="transaction" time="1.078" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted"/>
  <testcase name="transaction" time="0.894" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted"/>
  <testcase name="transaction" time="0.761" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted"/>
  <testcase name="transaction" time="0.863" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted"/>
  <testcase name="transaction" time="1.02" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted"/>
  <testcase name="transaction" time="5.06" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Correct Response Code of 635 is displayed for payment test of type Transaction has been Captured, Multiple captures not allowed. expected [635] but found [512]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Correct Response Code of 635 is displayed for payment test of type Transaction has been Captured, Multiple captures not allowed. expected [635] but found [512]
at com.concerto.common.utilities.Asserts.AssertAll(Asserts.java:191)
at com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted.transaction(CardedTransPGHosted.java:184)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- transaction -->
  <testcase name="transaction" time="5.671" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Correct Response Code of 636 is displayed for payment test of type Transaction has been Voided , Multiple voids not allowed. expected [636] but found [512]java.lang.AssertionError: Correct Response Code of 636 is displayed for payment test of type Transaction has been Voided , Multiple voids not allowed. expected [636] but found [512]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Correct Response Code of 636 is displayed for payment test of type Transaction has been Voided , Multiple voids not allowed. expected [636] but found [512]java.lang.AssertionError: Correct Response Code of 636 is displayed for payment test of type Transaction has been Voided , Multiple voids not allowed. expected [636] but found [512]
at com.concerto.common.utilities.Asserts.AssertAll(Asserts.java:191)
at com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted.transaction(CardedTransPGHosted.java:184)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- transaction -->
  <testcase name="transaction" time="4.472" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Capture expected [000] but found [512]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Capture expected [000] but found [512]
at com.concerto.common.utilities.Asserts.AssertAll(Asserts.java:191)
at com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted.transaction(CardedTransPGHosted.java:184)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- transaction -->
  <testcase name="transaction" time="3.913" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Refund(Pre-auth) expected [000] but found [644]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Refund(Pre-auth) expected [000] but found [644]
at com.concerto.common.utilities.Asserts.AssertAll(Asserts.java:191)
at com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted.transaction(CardedTransPGHosted.java:184)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- transaction -->
  <testcase name="transaction" time="5.809" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Refund(Pre-auth) expected [000] but found [512]java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Refund(Pre-auth) expected [000] but found [512]java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Refund(Pre-auth) expected [000] but found [512]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Refund(Pre-auth) expected [000] but found [512]java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Refund(Pre-auth) expected [000] but found [512]java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Refund(Pre-auth) expected [000] but found [512]
at com.concerto.common.utilities.Asserts.AssertAll(Asserts.java:191)
at com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted.transaction(CardedTransPGHosted.java:184)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- transaction -->
  <testcase name="transaction" time="3.692" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Refund(Purchase) expected [000] but found [644]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Refund(Purchase) expected [000] but found [644]
at com.concerto.common.utilities.Asserts.AssertAll(Asserts.java:191)
at com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted.transaction(CardedTransPGHosted.java:184)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- transaction -->
  <testcase name="transaction" time="5.9" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Refund(Purchase) expected [000] but found [512]java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Refund(Purchase) expected [000] but found [512]java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Refund(Purchase) expected [000] but found [512]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Refund(Purchase) expected [000] but found [512]java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Refund(Purchase) expected [000] but found [512]java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Refund(Purchase) expected [000] but found [512]
at com.concerto.common.utilities.Asserts.AssertAll(Asserts.java:191)
at com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted.transaction(CardedTransPGHosted.java:184)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- transaction -->
  <testcase name="transaction" time="0.938" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Purchase expected [000] but found [671]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Purchase expected [000] but found [671]
at com.concerto.common.utilities.Asserts.AssertAll(Asserts.java:191)
at com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted.transaction(CardedTransPGHosted.java:184)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- transaction -->
  <testcase name="transaction" time="5.164" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Pre-auth expected [000] but found [512]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Void Pre-auth expected [000] but found [512]
at com.concerto.common.utilities.Asserts.AssertAll(Asserts.java:191)
at com.concerto.vegaah.test.scenarios.apiTransactions.CardedTransPGHosted.transaction(CardedTransPGHosted.java:184)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- transaction -->
  <testcase name="@AfterSuite CompleteSuite" time="0.0" classname="com.concerto.common.BaseClass">
    <ignored/>
  </testcase> <!-- @AfterSuite CompleteSuite -->
  <testcase name="@BeforeSuite InitiateSuite" time="0.0" classname="com.concerto.common.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeSuite InitiateSuite -->
</testsuite> <!-- Reader Tests -->
