<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CSS-D-181" name="com.concerto.vegaah.test.scenarios.apiTransactions.CustomerNotPresentTrans" tests="1" failures="1" timestamp="26 Aug 2020 11:35:05 GMT" time="13.708" errors="0">
  <testcase name="transaction" time="13.708" classname="com.concerto.vegaah.test.scenarios.apiTransactions.CustomerNotPresentTrans">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Using CardToken  expected [000] but found [904]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction successful-Using CardToken  expected [000] but found [904]
at org.testng.Assert.fail(Assert.java:96)
at com.concerto.common.utilities.Asserts.AssertAll(Asserts.java:191)
at com.concerto.vegaah.test.scenarios.apiTransactions.CustomerNotPresentTrans.transaction(CustomerNotPresentTrans.java:89)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- transaction -->
</testsuite> <!-- com.concerto.vegaah.test.scenarios.apiTransactions.CustomerNotPresentTrans -->
