<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CSS-D-196" name="com.concerto.vegaah.test.scenarios.apiTransactions.ReportGenerationDataVoid" tests="3" failures="3" timestamp="03 Jun 2020 08:12:35 GMT" time="0.459" errors="0">
  <testcase name="transaction" time="0.158" classname="com.concerto.vegaah.test.scenarios.apiTransactions.ReportGenerationDataVoid">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction Successful for Capture Transaction expected [000] but found [null]java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction Successful for Void Purchase Transaction expected [000] but found [null]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction Successful for Capture Transaction expected [000] but found [null]java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction Successful for Void Purchase Transaction expected [000] but found [null]
at org.testng.Assert.fail(Assert.java:96)
at com.concerto.common.utilities.Asserts.AssertAll(Asserts.java:188)
at com.concerto.vegaah.test.scenarios.apiTransactions.ReportGenerationDataVoid.transaction(ReportGenerationDataVoid.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- transaction -->
  <testcase name="transaction" time="0.179" classname="com.concerto.vegaah.test.scenarios.apiTransactions.ReportGenerationDataVoid">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction Successful for Capture Transaction expected [000] but found [null]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction Successful for Capture Transaction expected [000] but found [null]
at org.testng.Assert.fail(Assert.java:96)
at com.concerto.common.utilities.Asserts.AssertAll(Asserts.java:188)
at com.concerto.vegaah.test.scenarios.apiTransactions.ReportGenerationDataVoid.transaction(ReportGenerationDataVoid.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- transaction -->
  <testcase name="transaction" time="0.122" classname="com.concerto.vegaah.test.scenarios.apiTransactions.ReportGenerationDataVoid">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction Successful for Capture Transaction expected [000] but found [null]java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction Successful for Void Purchase Transaction expected [000] but found [null]java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction Successful for Reversal Transaction expected [000] but found [null]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction Successful for Capture Transaction expected [000] but found [null]java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction Successful for Void Purchase Transaction expected [000] but found [null]java.lang.AssertionError: Correct Response Code of 000 is displayed for payment test of type Transaction Successful for Reversal Transaction expected [000] but found [null]
at org.testng.Assert.fail(Assert.java:96)
at com.concerto.common.utilities.Asserts.AssertAll(Asserts.java:188)
at com.concerto.vegaah.test.scenarios.apiTransactions.ReportGenerationDataVoid.transaction(ReportGenerationDataVoid.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- transaction -->
</testsuite> <!-- com.concerto.vegaah.test.scenarios.apiTransactions.ReportGenerationDataVoid -->
